name: GLuaTest Runner

on:
  pull_request:
    paths:
      - lua/**
  push:
    branches:
      - main
    paths:
      - lua/**
  workflow_dispatch:

jobs:
  run-mainbranch-tests:
    uses: RaphaelIT7/GLuaTest/.github/workflows/run_tests.yml@patch-1-test

  run-64bit-tests:
    uses: RaphaelIT7/GLuaTest/.github/workflows/run_tests.yml@patch-1-test
    with:
      branch: x86-64
